SAMPLE_RATE = 16000
AUDIO_CHUNK_SIZE = 1024
AUDIO_CHUNK_BYTES_FILE = 2048
WAV_CHANNELS = 1
WAV_SAMPLEWIDTH = 2
INT16_MAX = 32767
INT16_NORMALIZE = 32768.0
TEMP_AUDIO_DIR = "temp_audio"
STREAM_WARMUP_SEC = 0.3
TRANSCRIPT_POLL_INTERVAL = 0.2
AUDIO_PLAYER_POLL_INTERVAL = 0.5
WAVEFORM_DOWNSAMPLE_FACTOR = 10

VIOLENCE_ALERT_PREFIX = "__VIOLENCE_ALERT__:"
ERROR_PREFIX = "ERROR"

BIO_AGE_MIN, BIO_AGE_MAX = 15, 50
BIO_SYSTOLIC_MIN, BIO_SYSTOLIC_MAX = 80, 200
BIO_DIASTOLIC_MIN, BIO_DIASTOLIC_MAX = 50, 150
BIO_GLUCOSE_MIN, BIO_GLUCOSE_MAX = 3.0, 20.0
BIO_TEMP_MIN, BIO_TEMP_MAX = 95.0, 105.0
BIO_HR_MIN, BIO_HR_MAX = 40, 150

PDF_BP_SYSTOLIC_MIN, PDF_BP_SYSTOLIC_MAX = 50, 250
PDF_BP_DIASTOLIC_MIN, PDF_BP_DIASTOLIC_MAX = 30, 180
PDF_GLUCOSE_MIN, PDF_GLUCOSE_MAX = 3.0, 30.0
PDF_TEMP_FAHRENHEIT_MIN, PDF_TEMP_FAHRENHEIT_MAX = 95.0, 105.0
PDF_TEMP_CELSIUS_MIN, PDF_TEMP_CELSIUS_MAX = 35.0, 40.5
PDF_HR_MIN, PDF_HR_MAX = 40, 200
PDF_AGE_MIN, PDF_AGE_MAX = 15, 50

MHR_VALID_MIN, MHR_VALID_MAX = 40, 180
CONTEXT_WINDOW_SIZE = 5
MIN_TEXT_LENGTH_VIOLENCE = 10
VIOLENCE_THRESHOLD = 0.8
VIOLENCE_MAX_INPUT_CHARS = 512
VIOLENCE_MAX_LENGTH = 256

CHUNK_100MS_BYTES = 3200

# Sleep between consecutive audio chunks sent to AWS Transcribe Streaming.
# Keeps the WebSocket from being flooded while still matching real-time pace.
# 0.02 s gives ~5x better throughput vs the previous 0.15 s without dropping chunks.
SENDER_SLEEP_SEC = 0.02

# AWS S3 has strong read-after-write consistency (since Dec 2020), so no sleep
# is strictly required after an upload.  A minimal 0.1 s guard is kept only as
# a safety net for edge cases where a downstream AWS service (Textract, Transcribe)
# starts polling the object within milliseconds of creation.
S3_UPLOAD_PROPAGATION_WAIT = 0.1
